checkpoint_data:
  coins: 5
  bonus:
    first: 3
    second: 2
    third: 1

pvp:
  get-max-y: 152

  worldborder:
    center:
      x: 4.0
      z: 8.0

    size: 100

  spawn:
    0:
      x: 4.5
      y: 127.0
      z: 26.5
      pitch: 0.5
      yaw: -180
    1:
      x: 24.5
      y: 127.0
      z: 8.5
      pitch: 0.0
      yaw: 90.5
    2:
      x: 4.5
      y: 127.0
      z: -10.5
      pitch: -0.5
      yaw: 0.0
    3:
      x: -16.5
      y: 127.0
      z: 8.5
      pitch: 0.0
      yaw: -90
    4:
      x: -22.5
      y: 132.0
      z: 37.5
      pitch: 3.5
      yaw: -136.5
    5:
      x: 32.5
      y: 132.0
      z: 36.5
      pitch: 2.0
      yaw: 134.5
    6:
      x: 34.5
      y: 132.0
      z: -15.5
      pitch: 2.0
      yaw: 44.0
    7:
      x: -23.5
      y: 132.0
      z: -19.5
      pitch: 3.0
      yaw: -43.5
    8:
      x: -32.5
      y: 139.0
      z: 8.5
      pitch: 0
      yaw: -89.0
    9:
      x: 4.5
      y: 139.0
      z: 46.5
      pitch: -0.5
      yaw: -179.0
    10:
      x: 42.5
      y: 139.0
      z: 8.5
      pitch: 1.0
      yaw: 90.5
    11:
      x: 4.5
      y: 139.0
      z: -29.5
      pitch: 0.5
      yaw: -0.5

checkpoints:
  0:
    x: 19.5
    y: 113.5
    z: -123.5
    pitch: 0.0
    yaw: 0.0
  1:
    x: 15.5
    y: 128.0
    z: -20.5
    pitch: 20.0
    yaw: 35.0
  2:
    x: -0.5
    y: 116.0
    z: 57.5
    pitch: 0.0
    yaw: 0.0
  3:
    x: 0.5
    y: 121.0
    z: 99.5
    pitch: 0.0
    yaw: 0.0
  4:
    x: 0.5
    y: 138.0
    z: 173.5
    pitch: 0.0
    yaw: 0.0
  5:
    x: -4.5
    y: 137.0
    z: 277.5
    pitch: 0.0
    yaw: 0.0
  6:
    x: -1.5
    y: 143.0
    z: 341.5
    pitch: -10.0
    yaw: 80.0
  7:
    x: -9.5
    y: 170.0
    z: 350.5
    pitch: 0.0
    yaw: 0.0
  8:
    x: -5.5
    y: 193.0
    z: 353.5
    pitch: 5.0
    yaw: -135.0
  9:
    x: -2.5
    y: 81.0
    z: 409.5
    pitch: 0.0
    yaw: 90.0
  10:
    x: -5.5
    y: 71.0
    z: 475.5
    pitch: 0.0
    yaw: 0.0