checkpoint_data:
  coins: 5
  bonus:
    first: 3
    second: 2
    third: 1

checkpoints:
  world: ParkourPvP-Natura
  pos:
    0:
      x: -5.26
      y: 101
      z: 4.58
      pitch: -3.67
      yaw: -63.13
    1:
      x: 15.61
      y: 108
      z: 20.5
      pitch: 0.55
      yaw: 8.29
    2:
      x: -13.39
      y: 120
      z: 12.49
      pitch: 2.86
      yaw: 92.5
    3:
      x: 2.07
      y: 136
      z: -25.84
      pitch: -24.66
      yaw: -70.75
    4:
      x: 20.43
      y: 154
      z: 28.65
      pitch: -6.83
      yaw: 76.92
    5:
      x: -9.55
      y: 172
      z: -23.64
      pitch: -10.76
      yaw: -147.31
    6:
      x: 28.39
      y: 196
      z: 7.45
      pitch: -1.07
      yaw: 134.2
    7:
      x: 19.4
      y: 213
      z: -48.62
      pitch: -5.73
      yaw: -43.21
    8:
      x: 30.43
      y: 237
      z: -66.55
      pitch: 2.5
      yaw: 179.51
    9:
      x: 31.65
      y: 239
      z: -98.65
      pitch: 3.5
      yaw: 12.2
    10:
      x: 33.55
      y: 248
      z: -86.37
      pitch: -0.06
      yaw: -174.76