name: SkyBlock
description: Plugin for SkyBlock Server
author: LyFlow
main: net.lyflow.skyblock.SkyBlock
api-version: 1.19
version: 1.0.0-beta

commands:
  island:
    usage: §c/island <create/delete/config/tp/list> or /island <invite/kick/setowner/accept> <player>
    description: command to manipulate your island
    aliases: is

  visit:
    usage: §c/visit <player>
    description: command to visit other island

  lobby:
    usage: §c/lobby
    description: command to return to the lobby
    aliases: [spawn, hub]