name: QuillCraftBuild
version: 1.1
api-version: 1.20
author: LyFlow
main: net.quillcraft.build.QuillCraftBuild
depend: [QuillCraftCore]
commands:
  inventory:
    aliases: ["inv"]
    description: get or set inventory
    permission: quillcraft.build.inventory
    usage: "§c/inventory <get/set/remove> <name>"
  flightspeed:
    aliases: ["fl","fls"]
    description: change your flying speed
    permission: quillcraft.build.flyingspeed
    usage: "§c/flightspeed <speed> or /flightspeed to reset your flight speed"
  warp:
    aliases: ["w", "wp"]
    description: teleports you wherever you want
    permission: quillcraft.build.warp
    usage: "§c/warp <categorie> <zone>"
  createwarp:
    aliases: ["cw","cwp"]
    description: create a warp where you want
    permission: quillcraft.build.createwarp
    usage: "§c/createwarp <categorie> <zone>"
  removewarp:
    aliases: ["rw","remw"]
    description: remove a warp
    permission: quillcraft.build.removewarp
    usage: "§c/removewarp <categorie> <zone>"